version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
